apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
automountServiceAccountToken: false
